# Generated by Django 3.1.4 on 2020-12-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201221_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='accounts.group'),
        ),
    ]
