# Generated by Django 3.1.4 on 2021-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210113_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
