# Generated by Django 3.1.4 on 2020-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='max_attemps',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='time_to_complete',
            field=models.DurationField(),
        ),
    ]
