# Generated by Django 3.1.4 on 2020-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201223_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='assess_2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='assess_3',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='assess_4',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='assess_5',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='max_attemps',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
