# Generated by Django 3.1.4 on 2020-12-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201223_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points_for_question',
            field=models.PositiveIntegerField(),
        ),
    ]
