# Generated by Django 3.1.4 on 2021-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201223_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='time_to_complete',
            field=models.PositiveIntegerField(),
        ),
    ]
