# Generated by Django 3.1.4 on 2021-01-08 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210103_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
