# Generated by Django 3.1.4 on 2021-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210108_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresult',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
