# Generated by Django 3.1.4 on 2021-01-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210112_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
