# Generated by Django 3.1.4 on 2021-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_poll_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_started',
        ),
        migrations.AddField(
            model_name='pollresult',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollresult',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
