# Generated by Django 3.1.4 on 2021-01-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210113_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-active_from',)},
        ),
    ]
